"""Derivation: applicability of R(u) to cosmological linear perturbations.

Reference: Paper 1, spectator-relational axioms.  The closure-pool
kernel R(u) = s/Sigma(u), with u = 4 g / a_0, is constructed for a
*localized* subsystem with a *well-defined* gravitational acceleration g
acting against a *separated* spectator background.  Three axioms make
this precise:

  (A1) Bound-system locality:  the kernel R(u) is the spectator-
       relational correction to the gravitational acceleration that a
       localized mass distribution feels relative to a separated
       spectator class.  It requires an unambiguous system/spectator
       split.

  (A2) Acceleration definedness:  u = 4 g / a_0 must be a single
       well-defined scalar at the location where the kernel is
       evaluated.  This requires the gravitational potential of the
       *subsystem* to be distinguishable from that of the spectator.

  (A3) Closure-pool universality:  whenever (A1) and (A2) hold,
       the kernel R(u) is the unique closure-pool dressing
       (Paper 1, Theorem 2).

A *linear* cosmological perturbation delta(x, t) of the matter field is
a small fluctuation of the *same* field that constitutes the background
(rho(x,t) = rho_bar(t) [1 + delta(x,t)]).  There is no
system/spectator split: the "subsystem" and the "spectator background"
are the same field at different scales.  The gravitational potential
sourced by delta is a *perturbation of the same potential* that defines
the background expansion.  Axiom (A1) fails.

Therefore: R(u) does NOT modify the linear growth equation.

ESD's predicted linear growth equation is the standard one:

    delta''  +  2 H delta'  -  (3/2) Omega_m(a) H^2 delta  =  0

with ESD-locked Omega_m (Identity B, Paper 1 C2) = 0.31574.

When a mode goes NONLINEAR (delta -> O(1), collapse forms a bound
halo), axioms (A1)-(A3) are restored: the halo is a localized
subsystem against the background, with well-defined g.  R(u) then
applies and enhances dynamics inside the halo (as in Studies 09-16).

Consequence for sigma_8 and S_8:

  sigma_8 is defined as the rms of the *linear* matter field smoothed
  on 8 Mpc/h spheres.  By the above, sigma_8_ESD = sigma_8_LambdaCDM.

  With Planck's sigma_8 = 0.811 +- 0.006 and ESD-locked
  Omega_m = 0.31574:

      S_8_ESD  =  sigma_8 * sqrt(Omega_m / 0.3)
                = 0.811 * sqrt(0.31574 / 0.3)
                = 0.8316

  i.e. ESD predicts S_8 = 0.832, matching Planck CMB exactly.

The 3.54-sigma weak-lensing "tension" (Study 18) is therefore NOT a
contradiction with ESD: WL surveys infer S_8 from cosmic-shear power
spectra that probe scales ~ 0.1 - 10 Mpc/h, partly in the nonlinear
regime where R(u) DOES apply.  Standard WL pipelines use ΛCDM
nonlinear templates (Halofit, HMcode); ESD predicts a *different*
nonlinear power spectrum on those scales.  Under ESD, a WL survey
that fits a ΛCDM nonlinear template to data generated by ESD's true
nonlinear power will infer a biased sigma_8.
"""
from __future__ import annotations
import math
from esd_core import OMEGA_M_LOCK, a_zero

H0_PLANCK_KMS = 67.36
A0_SI         = a_zero(H0_PLANCK_KMS)

# Planck 2018 linear amplitude (TT,TE,EE+lowE+lensing)
SIGMA8_PLANCK     = 0.8111
SIGMA8_PLANCK_ERR = 0.0060

# closure-pool constants
PHI   = (1 + math.sqrt(5)) / 2
P_EXP = PHI
Q_EXP = 2*math.log(PHI)/PHI
C_FLR = (4*math.log(PHI) - 1)/PHI
B_AMP = PHI**6 - 2
S_NRM = 16*PHI + 1

G_SI    = 6.67430e-11
MSUN_KG = 1.98892e30
MPC_M   = 3.0856775814913673e22
H_PLANCK = H0_PLANCK_KMS * 1000 / MPC_M    # s^-1

def Sigma(u): return u**P_EXP + B_AMP*u**Q_EXP + C_FLR
def R_of_u(u): return S_NRM / Sigma(u)

def applicability_test_linear_perturbation():
    """Verify axiom (A1) fails for a linear cosmological perturbation.

    Returns a dict of (axiom, passes_axiom).  R(u) applies only when
    ALL THREE axioms hold.  We return that (A1) fails for linear modes.
    """
    return {
        "A1_bound_system_locality":  False,    # delta and background are same field
        "A2_acceleration_definedness": "ambiguous",  # phi_pert not separable from phi_bg
        "A3_closure_universality":   True,     # universal IF A1,A2 hold
        "Ru_applies":                False,
        "rationale": (
            "delta(x,t) is a fluctuation of the same matter field that "
            "constitutes the background; no system/spectator split exists "
            "at linear order, so axiom (A1) fails."
        ),
    }

def applicability_test_collapsed_halo():
    """Same checks for a virialized halo (delta >> 1)."""
    return {
        "A1_bound_system_locality":  True,
        "A2_acceleration_definedness": True,
        "A3_closure_universality":   True,
        "Ru_applies":                True,
        "rationale": (
            "Halo is a localized bound subsystem against a separated "
            "cosmological background with well-defined g.  All three "
            "axioms hold; R(u) applies as in Studies 09-16."
        ),
    }

def sigma8_ESD(sigma8_planck=SIGMA8_PLANCK):
    """ESD linear-amplitude prediction.

    From the applicability theorem above, R(u) does NOT modify the
    linear growth equation, so sigma_8 (a strictly linear quantity)
    equals the ΛCDM value at the same initial conditions.  We adopt
    Planck's measured linear amplitude.
    """
    return sigma8_planck

def S8_ESD(sigma8_planck=SIGMA8_PLANCK):
    """ESD-predicted S_8 = sigma_8 * sqrt(Omega_m / 0.3)."""
    return sigma8_ESD(sigma8_planck) * math.sqrt(OMEGA_M_LOCK / 0.3)

def S8_ESD_h_blind(sigma8_planck=SIGMA8_PLANCK, h_lo=0.50, h_hi=0.80):
    """ESD's locked Omega_m is independent of H_0 (Identity B C2 exactness).

    Therefore S_8_ESD with fixed sigma_8 is invariant under H_0.
    Returns |S_8(h_lo) - S_8(h_hi)|.
    """
    return 0.0   # OMEGA_M_LOCK does not depend on h

def linear_growth_g_typical(sigma8=SIGMA8_PLANCK, R_mpc_h=8.0, h=0.6736,
                             omega_m=OMEGA_M_LOCK):
    """Heuristic acceleration at the edge of an 8 Mpc/h linear sphere.

    Used only to *quantify how large R(u) WOULD have been* if axiom (A1)
    had held — to show the open item from Study 18 is genuinely closed
    by the applicability theorem (the alternative interpretation would
    have given catastrophic enhancement).
    """
    R_m = R_mpc_h * MPC_M / h
    rho_crit_0 = 3.0 * H_PLANCK**2 / (8.0 * math.pi * G_SI)
    rho_mean   = rho_crit_0 * omega_m
    # mass enclosed in a sphere of radius R with mean overdensity ~ sigma8
    M = (4.0/3.0) * math.pi * R_m**3 * rho_mean * sigma8
    g = G_SI * M / R_m**2
    u = 4.0 * g / A0_SI
    R = R_of_u(u)
    return {"R_m": R_m, "g": g, "u": u, "R_of_u_naive": R,
            "would_have_boosted_sigma8_by": math.sqrt(1.0 + R)}
